package com.example.apiweblaptop.dto;

public enum ErrorCode {
    FIND_CATEGORY_ERROR, GET_CATEGORY_ERROR, ADD_CATEGORY_ERROR, UPDATE_CATEGORY_ERROR, DELETE_CATEGORY_ERROR,
    FIND_PRODUCT_ERROR, GET_PRODUCT_ERROR, ADD_PRODUCT_ERROR, UPDATE_PRODUCT_ERROR, DELETE_PRODUCT_ERROR,
    FIND_ORDER_ERROR, GET_ORDER_ERROR, ADD_ORDER_ERROR, UPDATE_ORDER_ERROR, DELETE_ORDER_ERROR,
    FIND_USER_ERROR, GET_USER_ERROR, ADD_USER_ERROR, UPDATE_USER_ERROR, DELETE_USER_ERROR,
    FIND_STATUS_ERROR, GET_STATUS_ERROR, ADD_STATUS_ERROR, UPDATE_STATUS_ERROR, DELETE_STATUS_ERROR,
    FIND_ORDER_DETAIL_ERROR, GET_ORDER_DETAIL_ERROR, ADD_ORDER_DETAIL_ERROR, UPDATE_ORDER_DETAIL_ERROR, DELETE_ORDER_DETAIL_ERROR,
    FIND_USER_DETAIL_ERROR, GET_USER_DETAIL_ERROR, ADD_USER_DETAIL_ERROR, UPDATE_USER_DETAIL_ERROR, DELETE_USER_DETAIL_ERROR,
    FIND_PRODUCT_IMAGE_ERROR, GET_PRODUCT_IMAGE_ERROR, ADD_PRODUCT_IMAGE_ERROR, UPDATE_PRODUCT_IMAGE_ERROR, DELETE_PRODUCT_IMAGE_ERROR,
    FIND_PRODUCT_RATING_ERROR, GET_PRODUCT_RATING_ERROR, ADD_PRODUCT_RATING_ERROR, UPDATE_PRODUCT_RATING_ERROR, DELETE_PRODUCT_RATING_ERROR,
    FIND_BRAND_ERROR, GET_BRAND_ERROR, ADD_BRAND_ERROR, UPDATE_BRAND_ERROR, DELETE_BRAND_ERROR,
    GET_TOP_PRODUCT_ERROR, GET_DASHBOARD_ERROR,
    FIND_PHIEU_DAT_ERROR, GET_PHIEU_DAT_ERROR, ADD_PHIEU_DAT_ERROR, UPDATE_PHIEU_DAT_ERROR, DELETE_PHIEU_DAT_ERROR,
    FIND_CT_PHIEU_DAT_ERROR, GET_CT_PHIEU_DAT_ERROR, ADD_CT_PHIEU_DAT_ERROR, UPDATE_CT_PHIEU_DAT_ERROR, DELETE_CT_PHIEU_DAT_ERROR,
    FIND_PHIEU_NHAP_ERROR, GET_PHIEU_NHAP_ERROR, ADD_PHIEU_NHAP_ERROR, UPDATE_PHIEU_NHAP_ERROR, DELETE_PHIEU_NHAP_ERROR,
    FIND_CT_PHIEU_NHAP_ERROR, GET_CT_PHIEU_NHAP_ERROR, ADD_CT_PHIEU_NHAP_ERROR, UPDATE_CT_PHIEU_NHAP_ERROR, DELETE_CT_PHIEU_NHAP_ERROR,
}
