package com.example.apiweblaptop.dto;

public enum SuccessCode {
    FIND_CATEGORY_SUCCESS, GET_ALL_CATEGORY_SUCCESS, ADD_CATEGORY_SUCCESS, UPDATE_CATEGORY_SUCCESS, DELETE_CATEGORY_SUCCESS,
    FIND_PRODUCT_SUCCESS, GET_ALL_PRODUCT_SUCCESS, ADD_PRODUCT_SUCCESS, UPDATE_PRODUCT_SUCCESS, DELETE_PRODUCT_SUCCESS,
    FIND_ORDER_SUCCESS, GET_ALL_ORDER_SUCCESS, ADD_ORDER_SUCCESS, UPDATE_ORDER_SUCCESS, DELETE_ORDER_SUCCESS,
    FIND_USER_SUCCESS, GET_ALL_USER_SUCCESS, ADD_USER_SUCCESS, UPDATE_USER_SUCCESS, DELETE_USER_SUCCESS,
    FIND_STATUS_SUCCESS, GET_ALL_STATUS_SUCCESS, ADD_STATUS_SUCCESS, UPDATE_STATUS_SUCCESS, DELETE_STATUS_SUCCESS,
    FIND_ORDER_DETAIL_SUCCESS, GET_ALL_ORDER_DETAIL_SUCCESS, ADD_ORDER_DETAIL_SUCCESS, UPDATE_ORDER_DETAIL_SUCCESS, DELETE_ORDER_DETAIL_SUCCESS,
    FIND_USER_DETAIL_SUCCESS, GET_ALL_USER_DETAIL_SUCCESS, ADD_USER_DETAIL_SUCCESS, UPDATE_USER_DETAIL_SUCCESS, DELETE_USER_DETAIL_SUCCESS,
    FIND_PRODUCT_IMAGE_SUCCESS, GET_ALL_PRODUCT_IMAGE_SUCCESS, ADD_PRODUCT_IMAGE_SUCCESS, UPDATE_PRODUCT_IMAGE_SUCCESS, DELETE_PRODUCT_IMAGE_SUCCESS,
    FIND_PRODUCT_RATING_SUCCESS, GET_ALL_PRODUCT_RATING_SUCCESS, ADD_PRODUCT_RATING_SUCCESS, UPDATE_PRODUCT_RATING_SUCCESS, DELETE_PRODUCT_RATING_SUCCESS,
    FIND_BRAND_SUCCESS, GET_ALL_BRAND_SUCCESS, ADD_BRAND_SUCCESS, UPDATE_BRAND_SUCCESS, DELETE_BRAND_SUCCESS,
    GET_TOP_PRODUCT_SUCCESS, GET_DASHBOARD_SUCCESS,
    FIND_PHIEU_DAT_SUCCESS, GET_ALL_PHIEU_DAT_SUCCESS, ADD_PHIEU_DAT_SUCCESS, UPDATE_PHIEU_DAT_SUCCESS, DELETE_PHIEU_DAT_SUCCESS,
    FIND_CT_PHIEU_DAT_SUCCESS, GET_ALL_CT_PHIEU_DAT_SUCCESS, ADD_CT_PHIEU_DAT_SUCCESS, UPDATE_CT_PHIEU_DAT_SUCCESS, DELETE_CT_PHIEU_DAT_SUCCESS,
    FIND_PHIEU_NHAP_SUCCESS, GET_ALL_PHIEU_NHAP_SUCCESS, ADD_PHIEU_NHAP_SUCCESS, UPDATE_PHIEU_NHAP_SUCCESS, DELETE_PHIEU_NHAP_SUCCESS,
    FIND_CT_PHIEU_NHAP_SUCCESS, GET_ALL_CT_PHIEU_NHAP_SUCCESS, ADD_CT_PHIEU_NHAP_SUCCESS, UPDATE_CT_PHIEU_NHAP_SUCCESS, DELETE_CT_PHIEU_NHAP_SUCCESS,
}
